# Generated by Django 5.0.6 on 2026-05-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_created_at_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la routine')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('discount_percentage', models.IntegerField(default=10, help_text='Pourcentage de réduction si achetée complète', verbose_name='Réduction (%)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='routines/', verbose_name='Image de couverture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Routine Beauté',
                'verbose_name_plural': 'Routines Beauté',
            },
        ),
        migrations.CreateModel(
            name='RoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=1, verbose_name="Numéro de l'étape")),
                ('instructions', models.TextField(blank=True, help_text='Ex: Appliquer sur cheveux humides...', verbose_name="Instructions d'utilisation")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produit')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.routine')),
            ],
            options={
                'verbose_name': 'Étape de Routine',
                'verbose_name_plural': 'Étapes de Routine',
                'ordering': ['step_number'],
            },
        ),
    ]
