# Generated by Django 5.0.6 on 2026-05-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_routine_routineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reviews/media/', verbose_name='Image ou Vidéo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='products.review')),
            ],
            options={
                'verbose_name': "Média d'Avis",
                'verbose_name_plural': "Médias d'Avis",
            },
        ),
    ]
