# Generated by Django 5.0.6 on 2026-05-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube, TikTok, etc.', max_length=500, null=True),
        ),
    ]
