# Generated by Django 5.0.6 on 2026-05-30 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_city_alter_order_email_and_more'),
        ('products', '0004_reviewmedia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('1_MONTH', 'Chaque mois'), ('2_MONTHS', 'Tous les 2 mois'), ('3_MONTHS', 'Tous les 3 mois')], default='1_MONTH', max_length=20, verbose_name='Fréquence de livraison')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('next_delivery_date', models.DateField(verbose_name='Prochaine livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produit abonné')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
    ]
