# Generated by Django 5.0.6 on 2026-05-30 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_type', models.CharField(blank=True, choices=[('1', 'Lisse (1)'), ('2', 'Ondulé (2A, 2B, 2C)'), ('3', 'Bouclé (3A, 3B, 3C)'), ('4', 'Crépu (4A, 4B, 4C)')], max_length=20, null=True, verbose_name='Type de cheveux')),
                ('hair_porosity', models.CharField(blank=True, choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('FORTE', 'Forte')], max_length=20, null=True, verbose_name='Porosité')),
                ('skin_type', models.CharField(blank=True, choices=[('SECHE', 'Sèche'), ('GRASSE', 'Grasse'), ('MIXTE', 'Mixte'), ('NORMALE', 'Normale')], max_length=20, null=True, verbose_name='Type de peau')),
                ('primary_concern', models.CharField(blank=True, help_text='Ex: Hydratation, Pousse, Acné...', max_length=255, null=True, verbose_name='Préoccupation principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Beauté',
                'verbose_name_plural': 'Profils Beauté',
            },
        ),
    ]
