# Generated by Django 5.0.6 on 2026-05-30 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_beautyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points de fidélité')),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Argent'), ('GOLD', 'Or'), ('DIAMOND', 'Diamant')], default='BRONZE', max_length=50, verbose_name='Statut VIP')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total dépensé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte Fidélité',
                'verbose_name_plural': 'Comptes Fidélité',
            },
        ),
    ]
